#!/bin/bash
# Wrapper that translates colon syntax to Make targets.
#
# Usage:
#   ./run test                     run all tests
#   ./run test:skyfs               all skyfs tests
#   ./run test:skyfs:cli           Go tests
#   ./run test:skyfs:ui:macos      Swift tests
#   ./run build                    build Go binary
#   ./run build:swift              build Swift library
#
# Translates colons to dashes and forwards to make.

target=$(echo "$1" | tr ':' '-')
shift 2>/dev/null
exec make "$target" "$@"
