name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-go:
    name: Go tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: make check
      - run: make test-skyfs-cli

  test-swift:
    name: Swift tests (macOS)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - run: make test-skyfs-ui-macos
