import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#0058bc",
        "primary-container": "#0070eb",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#fefcff",
        "on-primary-fixed": "#001a41",
        "on-primary-fixed-variant": "#004493",
        secondary: "#5d5e63",
        "secondary-container": "#e0dfe4",
        "secondary-fixed": "#e3e2e7",
        "secondary-fixed-dim": "#c6c6cb",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#626267",
        "on-secondary-fixed": "#1a1b1f",
        "on-secondary-fixed-variant": "#46464b",
        tertiary: "#9e3d00",
        "tertiary-container": "#c64f00",
        "tertiary-fixed": "#ffdbcc",
        "tertiary-fixed-dim": "#ffb595",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#fffbff",
        "on-tertiary-fixed": "#351000",
        "on-tertiary-fixed-variant": "#7c2e00",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        surface: "#f9f9fb",
        "surface-dim": "#d9dadc",
        "surface-bright": "#f9f9fb",
        "surface-variant": "#e2e2e4",
        "surface-container": "#eeeef0",
        "surface-container-low": "#f3f3f5",
        "surface-container-high": "#e8e8ea",
        "surface-container-highest": "#e2e2e4",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#005bc1",
        "on-surface": "#1a1c1d",
        "on-surface-variant": "#414755",
        background: "#f9f9fb",
        "on-background": "#1a1c1d",
        outline: "#717786",
        "outline-variant": "#c1c6d7",
        "inverse-surface": "#2f3132",
        "inverse-on-surface": "#f0f0f2",
        "inverse-primary": "#adc6ff",
      },
      fontFamily: {
        headline: ["Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
        mono: ["Roboto Mono", "ui-monospace", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "1.25rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
