import type { Config } from "tailwindcss";

const colorVar = (name: string) => `rgb(var(--color-${name}) / <alpha-value>)`;

const config: Config = {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: colorVar("primary"),
        "primary-container": colorVar("primary-container"),
        "primary-fixed": colorVar("primary-fixed"),
        "primary-fixed-dim": colorVar("primary-fixed-dim"),
        "on-primary": colorVar("on-primary"),
        "on-primary-container": colorVar("on-primary-container"),
        "on-primary-fixed": colorVar("on-primary-fixed"),
        "on-primary-fixed-variant": colorVar("on-primary-fixed-variant"),
        secondary: colorVar("secondary"),
        "secondary-container": colorVar("secondary-container"),
        "secondary-fixed": colorVar("secondary-fixed"),
        "secondary-fixed-dim": colorVar("secondary-fixed-dim"),
        "on-secondary": colorVar("on-secondary"),
        "on-secondary-container": colorVar("on-secondary-container"),
        "on-secondary-fixed": colorVar("on-secondary-fixed"),
        "on-secondary-fixed-variant": colorVar("on-secondary-fixed-variant"),
        tertiary: colorVar("tertiary"),
        "tertiary-container": colorVar("tertiary-container"),
        "tertiary-fixed": colorVar("tertiary-fixed"),
        "tertiary-fixed-dim": colorVar("tertiary-fixed-dim"),
        "on-tertiary": colorVar("on-tertiary"),
        "on-tertiary-container": colorVar("on-tertiary-container"),
        "on-tertiary-fixed": colorVar("on-tertiary-fixed"),
        "on-tertiary-fixed-variant": colorVar("on-tertiary-fixed-variant"),
        error: colorVar("error"),
        "error-container": colorVar("error-container"),
        "on-error": colorVar("on-error"),
        "on-error-container": colorVar("on-error-container"),
        surface: colorVar("surface"),
        "surface-dim": colorVar("surface-dim"),
        "surface-bright": colorVar("surface-bright"),
        "surface-variant": colorVar("surface-variant"),
        "surface-container": colorVar("surface-container"),
        "surface-container-low": colorVar("surface-container-low"),
        "surface-container-high": colorVar("surface-container-high"),
        "surface-container-highest": colorVar("surface-container-highest"),
        "surface-container-lowest": colorVar("surface-container-lowest"),
        "surface-tint": colorVar("surface-tint"),
        "on-surface": colorVar("on-surface"),
        "on-surface-variant": colorVar("on-surface-variant"),
        background: colorVar("background"),
        "on-background": colorVar("on-background"),
        outline: colorVar("outline"),
        "outline-variant": colorVar("outline-variant"),
        "inverse-surface": colorVar("inverse-surface"),
        "inverse-on-surface": colorVar("inverse-on-surface"),
        "inverse-primary": colorVar("inverse-primary"),
      },
      fontFamily: {
        headline: ["Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Inter", "system-ui", "sans-serif"],
        mono: ["Roboto Mono", "ui-monospace", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "1rem",
        xl: "1.25rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
